# Generated by Django 5.2.5 on 2025-09-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='year_level',
            field=models.IntegerField(),
        ),
    ]
